# 本地配置文件
spring:
  profiles:
    active: dev
  application:
    name: yiban-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yao-usercenter
    username: root
    password: 6825
  # session 失效时间
  session:
    timeout: 86400
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8088
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）